// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/services/pruning/v1beta1/pruning.proto

package cometbft_services_pruning_v1beta1

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SetBlockRetainHeightRequest struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *SetBlockRetainHeightRequest) Reset()         { *m = SetBlockRetainHeightRequest{} }
func (m *SetBlockRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*SetBlockRetainHeightRequest) ProtoMessage()    {}
func (*SetBlockRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{0}
}
func (m *SetBlockRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetBlockRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetBlockRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetBlockRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBlockRetainHeightRequest.Merge(m, src)
}
func (m *SetBlockRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetBlockRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBlockRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBlockRetainHeightRequest proto.InternalMessageInfo

func (m *SetBlockRetainHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SetBlockRetainHeightResponse struct {
}

func (m *SetBlockRetainHeightResponse) Reset()         { *m = SetBlockRetainHeightResponse{} }
func (m *SetBlockRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*SetBlockRetainHeightResponse) ProtoMessage()    {}
func (*SetBlockRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{1}
}
func (m *SetBlockRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetBlockRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetBlockRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetBlockRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBlockRetainHeightResponse.Merge(m, src)
}
func (m *SetBlockRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *SetBlockRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBlockRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetBlockRetainHeightResponse proto.InternalMessageInfo

type GetBlockRetainHeightRequest struct {
}

func (m *GetBlockRetainHeightRequest) Reset()         { *m = GetBlockRetainHeightRequest{} }
func (m *GetBlockRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRetainHeightRequest) ProtoMessage()    {}
func (*GetBlockRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{2}
}
func (m *GetBlockRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBlockRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRetainHeightRequest.Merge(m, src)
}
func (m *GetBlockRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRetainHeightRequest proto.InternalMessageInfo

type GetBlockRetainHeightResponse struct {
	// The retain height set by the application.
	AppRetainHeight uint64 `protobuf:"varint,1,opt,name=app_retain_height,json=appRetainHeight,proto3" json:"app_retain_height,omitempty"`
	// The retain height set via the pruning service (e.g. by the data
	// companion) specifically for blocks.
	PruningServiceRetainHeight uint64 `protobuf:"varint,2,opt,name=pruning_service_retain_height,json=pruningServiceRetainHeight,proto3" json:"pruning_service_retain_height,omitempty"`
}

func (m *GetBlockRetainHeightResponse) Reset()         { *m = GetBlockRetainHeightResponse{} }
func (m *GetBlockRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockRetainHeightResponse) ProtoMessage()    {}
func (*GetBlockRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{3}
}
func (m *GetBlockRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBlockRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRetainHeightResponse.Merge(m, src)
}
func (m *GetBlockRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRetainHeightResponse proto.InternalMessageInfo

func (m *GetBlockRetainHeightResponse) GetAppRetainHeight() uint64 {
	if m != nil {
		return m.AppRetainHeight
	}
	return 0
}

func (m *GetBlockRetainHeightResponse) GetPruningServiceRetainHeight() uint64 {
	if m != nil {
		return m.PruningServiceRetainHeight
	}
	return 0
}

type SetBlockResultsRetainHeightRequest struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *SetBlockResultsRetainHeightRequest) Reset()         { *m = SetBlockResultsRetainHeightRequest{} }
func (m *SetBlockResultsRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*SetBlockResultsRetainHeightRequest) ProtoMessage()    {}
func (*SetBlockResultsRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{4}
}
func (m *SetBlockResultsRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetBlockResultsRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetBlockResultsRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetBlockResultsRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBlockResultsRetainHeightRequest.Merge(m, src)
}
func (m *SetBlockResultsRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetBlockResultsRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBlockResultsRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBlockResultsRetainHeightRequest proto.InternalMessageInfo

func (m *SetBlockResultsRetainHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SetBlockResultsRetainHeightResponse struct {
}

func (m *SetBlockResultsRetainHeightResponse) Reset()         { *m = SetBlockResultsRetainHeightResponse{} }
func (m *SetBlockResultsRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*SetBlockResultsRetainHeightResponse) ProtoMessage()    {}
func (*SetBlockResultsRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{5}
}
func (m *SetBlockResultsRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetBlockResultsRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetBlockResultsRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetBlockResultsRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBlockResultsRetainHeightResponse.Merge(m, src)
}
func (m *SetBlockResultsRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *SetBlockResultsRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBlockResultsRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetBlockResultsRetainHeightResponse proto.InternalMessageInfo

type GetBlockResultsRetainHeightRequest struct {
}

func (m *GetBlockResultsRetainHeightRequest) Reset()         { *m = GetBlockResultsRetainHeightRequest{} }
func (m *GetBlockResultsRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockResultsRetainHeightRequest) ProtoMessage()    {}
func (*GetBlockResultsRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{6}
}
func (m *GetBlockResultsRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockResultsRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockResultsRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBlockResultsRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResultsRetainHeightRequest.Merge(m, src)
}
func (m *GetBlockResultsRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockResultsRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResultsRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResultsRetainHeightRequest proto.InternalMessageInfo

type GetBlockResultsRetainHeightResponse struct {
	// The retain height set by the pruning service (e.g. by the data
	// companion) specifically for block results.
	PruningServiceRetainHeight uint64 `protobuf:"varint,1,opt,name=pruning_service_retain_height,json=pruningServiceRetainHeight,proto3" json:"pruning_service_retain_height,omitempty"`
}

func (m *GetBlockResultsRetainHeightResponse) Reset()         { *m = GetBlockResultsRetainHeightResponse{} }
func (m *GetBlockResultsRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResultsRetainHeightResponse) ProtoMessage()    {}
func (*GetBlockResultsRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{7}
}
func (m *GetBlockResultsRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockResultsRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockResultsRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBlockResultsRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResultsRetainHeightResponse.Merge(m, src)
}
func (m *GetBlockResultsRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockResultsRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResultsRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResultsRetainHeightResponse proto.InternalMessageInfo

func (m *GetBlockResultsRetainHeightResponse) GetPruningServiceRetainHeight() uint64 {
	if m != nil {
		return m.PruningServiceRetainHeight
	}
	return 0
}

type SetTxIndexerRetainHeightRequest struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *SetTxIndexerRetainHeightRequest) Reset()         { *m = SetTxIndexerRetainHeightRequest{} }
func (m *SetTxIndexerRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*SetTxIndexerRetainHeightRequest) ProtoMessage()    {}
func (*SetTxIndexerRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{8}
}
func (m *SetTxIndexerRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetTxIndexerRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetTxIndexerRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetTxIndexerRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTxIndexerRetainHeightRequest.Merge(m, src)
}
func (m *SetTxIndexerRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetTxIndexerRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTxIndexerRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTxIndexerRetainHeightRequest proto.InternalMessageInfo

func (m *SetTxIndexerRetainHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SetTxIndexerRetainHeightResponse struct {
}

func (m *SetTxIndexerRetainHeightResponse) Reset()         { *m = SetTxIndexerRetainHeightResponse{} }
func (m *SetTxIndexerRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*SetTxIndexerRetainHeightResponse) ProtoMessage()    {}
func (*SetTxIndexerRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{9}
}
func (m *SetTxIndexerRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetTxIndexerRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetTxIndexerRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetTxIndexerRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTxIndexerRetainHeightResponse.Merge(m, src)
}
func (m *SetTxIndexerRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *SetTxIndexerRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTxIndexerRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTxIndexerRetainHeightResponse proto.InternalMessageInfo

type GetTxIndexerRetainHeightRequest struct {
}

func (m *GetTxIndexerRetainHeightRequest) Reset()         { *m = GetTxIndexerRetainHeightRequest{} }
func (m *GetTxIndexerRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetTxIndexerRetainHeightRequest) ProtoMessage()    {}
func (*GetTxIndexerRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{10}
}
func (m *GetTxIndexerRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTxIndexerRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTxIndexerRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTxIndexerRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIndexerRetainHeightRequest.Merge(m, src)
}
func (m *GetTxIndexerRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTxIndexerRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIndexerRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIndexerRetainHeightRequest proto.InternalMessageInfo

type GetTxIndexerRetainHeightResponse struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *GetTxIndexerRetainHeightResponse) Reset()         { *m = GetTxIndexerRetainHeightResponse{} }
func (m *GetTxIndexerRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxIndexerRetainHeightResponse) ProtoMessage()    {}
func (*GetTxIndexerRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{11}
}
func (m *GetTxIndexerRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTxIndexerRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTxIndexerRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTxIndexerRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIndexerRetainHeightResponse.Merge(m, src)
}
func (m *GetTxIndexerRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetTxIndexerRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIndexerRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIndexerRetainHeightResponse proto.InternalMessageInfo

func (m *GetTxIndexerRetainHeightResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SetBlockIndexerRetainHeightRequest struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *SetBlockIndexerRetainHeightRequest) Reset()         { *m = SetBlockIndexerRetainHeightRequest{} }
func (m *SetBlockIndexerRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*SetBlockIndexerRetainHeightRequest) ProtoMessage()    {}
func (*SetBlockIndexerRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{12}
}
func (m *SetBlockIndexerRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetBlockIndexerRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetBlockIndexerRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetBlockIndexerRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBlockIndexerRetainHeightRequest.Merge(m, src)
}
func (m *SetBlockIndexerRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetBlockIndexerRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBlockIndexerRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBlockIndexerRetainHeightRequest proto.InternalMessageInfo

func (m *SetBlockIndexerRetainHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SetBlockIndexerRetainHeightResponse struct {
}

func (m *SetBlockIndexerRetainHeightResponse) Reset()         { *m = SetBlockIndexerRetainHeightResponse{} }
func (m *SetBlockIndexerRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*SetBlockIndexerRetainHeightResponse) ProtoMessage()    {}
func (*SetBlockIndexerRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{13}
}
func (m *SetBlockIndexerRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetBlockIndexerRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetBlockIndexerRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetBlockIndexerRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBlockIndexerRetainHeightResponse.Merge(m, src)
}
func (m *SetBlockIndexerRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *SetBlockIndexerRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBlockIndexerRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetBlockIndexerRetainHeightResponse proto.InternalMessageInfo

type GetBlockIndexerRetainHeightRequest struct {
}

func (m *GetBlockIndexerRetainHeightRequest) Reset()         { *m = GetBlockIndexerRetainHeightRequest{} }
func (m *GetBlockIndexerRetainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockIndexerRetainHeightRequest) ProtoMessage()    {}
func (*GetBlockIndexerRetainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{14}
}
func (m *GetBlockIndexerRetainHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockIndexerRetainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockIndexerRetainHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBlockIndexerRetainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockIndexerRetainHeightRequest.Merge(m, src)
}
func (m *GetBlockIndexerRetainHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockIndexerRetainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockIndexerRetainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockIndexerRetainHeightRequest proto.InternalMessageInfo

type GetBlockIndexerRetainHeightResponse struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *GetBlockIndexerRetainHeightResponse) Reset()         { *m = GetBlockIndexerRetainHeightResponse{} }
func (m *GetBlockIndexerRetainHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockIndexerRetainHeightResponse) ProtoMessage()    {}
func (*GetBlockIndexerRetainHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7bfde54a194a92, []int{15}
}
func (m *GetBlockIndexerRetainHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockIndexerRetainHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockIndexerRetainHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBlockIndexerRetainHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockIndexerRetainHeightResponse.Merge(m, src)
}
func (m *GetBlockIndexerRetainHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockIndexerRetainHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockIndexerRetainHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockIndexerRetainHeightResponse proto.InternalMessageInfo

func (m *GetBlockIndexerRetainHeightResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*SetBlockRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.SetBlockRetainHeightRequest")
	proto.RegisterType((*SetBlockRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.SetBlockRetainHeightResponse")
	proto.RegisterType((*GetBlockRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.GetBlockRetainHeightRequest")
	proto.RegisterType((*GetBlockRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.GetBlockRetainHeightResponse")
	proto.RegisterType((*SetBlockResultsRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.SetBlockResultsRetainHeightRequest")
	proto.RegisterType((*SetBlockResultsRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.SetBlockResultsRetainHeightResponse")
	proto.RegisterType((*GetBlockResultsRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.GetBlockResultsRetainHeightRequest")
	proto.RegisterType((*GetBlockResultsRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.GetBlockResultsRetainHeightResponse")
	proto.RegisterType((*SetTxIndexerRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.SetTxIndexerRetainHeightRequest")
	proto.RegisterType((*SetTxIndexerRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.SetTxIndexerRetainHeightResponse")
	proto.RegisterType((*GetTxIndexerRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.GetTxIndexerRetainHeightRequest")
	proto.RegisterType((*GetTxIndexerRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.GetTxIndexerRetainHeightResponse")
	proto.RegisterType((*SetBlockIndexerRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.SetBlockIndexerRetainHeightRequest")
	proto.RegisterType((*SetBlockIndexerRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.SetBlockIndexerRetainHeightResponse")
	proto.RegisterType((*GetBlockIndexerRetainHeightRequest)(nil), "cometbft.services.pruning.v1beta1.GetBlockIndexerRetainHeightRequest")
	proto.RegisterType((*GetBlockIndexerRetainHeightResponse)(nil), "cometbft.services.pruning.v1beta1.GetBlockIndexerRetainHeightResponse")
}

func init() {
	proto.RegisterFile("cometbft/services/pruning/v1beta1/pruning.proto", fileDescriptor_4b7bfde54a194a92)
}

var fileDescriptor_4b7bfde54a194a92 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x31, 0x4f, 0xb3, 0x40,
	0x18, 0xc7, 0x7b, 0x6f, 0xde, 0x74, 0x78, 0x16, 0x23, 0x83, 0x69, 0x6c, 0x7b, 0x6d, 0xaf, 0x9a,
	0x18, 0x87, 0x92, 0xc6, 0x38, 0x68, 0x74, 0xb0, 0xcb, 0xe9, 0xda, 0xba, 0x13, 0xc0, 0xc7, 0x42,
	0xac, 0x70, 0x72, 0x47, 0xd3, 0x2f, 0x61, 0xe2, 0xc7, 0x72, 0xec, 0xe8, 0x68, 0xe0, 0x8b, 0x98,
	0xe0, 0x91, 0xa2, 0x11, 0x48, 0x3b, 0x1e, 0x3c, 0xbf, 0x3f, 0xf7, 0x7b, 0xfe, 0x01, 0x4c, 0x37,
	0x7c, 0x46, 0xe5, 0x3c, 0x2a, 0x53, 0x62, 0xb4, 0xf4, 0x5d, 0x94, 0xa6, 0x88, 0xe2, 0xc0, 0x0f,
	0xe6, 0xe6, 0x72, 0xec, 0xa0, 0xb2, 0xc7, 0xf9, 0x79, 0x24, 0xa2, 0x50, 0x85, 0xc6, 0x20, 0x07,
	0x46, 0x39, 0x30, 0xca, 0x07, 0x34, 0xc0, 0xce, 0xa1, 0x3d, 0x43, 0x35, 0x59, 0x84, 0xee, 0xd3,
	0x14, 0x95, 0xed, 0x07, 0xb7, 0xe8, 0xcf, 0x3d, 0x35, 0xc5, 0x97, 0x18, 0xa5, 0x32, 0x0e, 0xa0,
	0xe9, 0x65, 0x0f, 0x5a, 0xa4, 0x4f, 0x4e, 0xfe, 0x4f, 0xf5, 0x89, 0x51, 0xe8, 0xfc, 0x8d, 0x49,
	0x11, 0x06, 0x12, 0x59, 0x17, 0xda, 0xbc, 0x3c, 0x96, 0xbd, 0x12, 0xe8, 0xf0, 0x0a, 0xde, 0x38,
	0x85, 0x7d, 0x5b, 0x08, 0x2b, 0xca, 0xde, 0x59, 0x3f, 0xae, 0xb0, 0x67, 0x0b, 0x51, 0x64, 0x8c,
	0x1b, 0xe8, 0x6a, 0x2b, 0x4b, 0x6b, 0xfe, 0xe2, 0xfe, 0x65, 0xdc, 0xa1, 0x1e, 0x9a, 0x7d, 0xcf,
	0x14, 0x23, 0xd8, 0x15, 0xb0, 0x8d, 0x8e, 0x8c, 0x17, 0x4a, 0x6e, 0xb3, 0x8c, 0x63, 0x18, 0x56,
	0xd2, 0x7a, 0x27, 0x47, 0xc0, 0x78, 0xed, 0x47, 0x98, 0x07, 0x43, 0x5e, 0x1f, 0x56, 0x2f, 0x4d,
	0x6a, 0xa5, 0x2f, 0xa0, 0x37, 0x43, 0x75, 0xbf, 0xba, 0x0b, 0x1e, 0x70, 0x85, 0xd1, 0x36, 0xc6,
	0x0c, 0xfa, 0xe5, 0xa8, 0xd6, 0x1d, 0x40, 0x8f, 0x57, 0xc7, 0xb3, 0x4b, 0xe8, 0xf3, 0x9a, 0x98,
	0xd2, 0x2b, 0x14, 0x2a, 0xdb, 0x41, 0xa0, 0x50, 0x59, 0x95, 0x43, 0xa1, 0xb2, 0x0a, 0x8d, 0xeb,
	0x4d, 0x65, 0x3b, 0x98, 0x4c, 0x5a, 0xef, 0x09, 0x25, 0xeb, 0x84, 0x92, 0xcf, 0x84, 0x92, 0xb7,
	0x94, 0x36, 0xd6, 0x29, 0x6d, 0x7c, 0xa4, 0xb4, 0xe1, 0x34, 0xb3, 0xdf, 0xf8, 0xec, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x28, 0xfc, 0x88, 0x0f, 0xf9, 0x03, 0x00, 0x00,
}

func (m *SetBlockRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetBlockRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetBlockRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetBlockRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetBlockRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetBlockRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBlockRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBlockRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBlockRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBlockRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PruningServiceRetainHeight != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.PruningServiceRetainHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.AppRetainHeight != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.AppRetainHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetBlockResultsRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetBlockResultsRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetBlockResultsRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetBlockResultsRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetBlockResultsRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetBlockResultsRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBlockResultsRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockResultsRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBlockResultsRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBlockResultsRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockResultsRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBlockResultsRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PruningServiceRetainHeight != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.PruningServiceRetainHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetTxIndexerRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetTxIndexerRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetTxIndexerRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetTxIndexerRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetTxIndexerRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetTxIndexerRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetTxIndexerRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTxIndexerRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTxIndexerRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetTxIndexerRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTxIndexerRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTxIndexerRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetBlockIndexerRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetBlockIndexerRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetBlockIndexerRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetBlockIndexerRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetBlockIndexerRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetBlockIndexerRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBlockIndexerRetainHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockIndexerRetainHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBlockIndexerRetainHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBlockIndexerRetainHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockIndexerRetainHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBlockIndexerRetainHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintPruning(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPruning(dAtA []byte, offset int, v uint64) int {
	offset -= sovPruning(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SetBlockRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovPruning(uint64(m.Height))
	}
	return n
}

func (m *SetBlockRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBlockRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBlockRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppRetainHeight != 0 {
		n += 1 + sovPruning(uint64(m.AppRetainHeight))
	}
	if m.PruningServiceRetainHeight != 0 {
		n += 1 + sovPruning(uint64(m.PruningServiceRetainHeight))
	}
	return n
}

func (m *SetBlockResultsRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovPruning(uint64(m.Height))
	}
	return n
}

func (m *SetBlockResultsRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBlockResultsRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBlockResultsRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PruningServiceRetainHeight != 0 {
		n += 1 + sovPruning(uint64(m.PruningServiceRetainHeight))
	}
	return n
}

func (m *SetTxIndexerRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovPruning(uint64(m.Height))
	}
	return n
}

func (m *SetTxIndexerRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetTxIndexerRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetTxIndexerRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovPruning(uint64(m.Height))
	}
	return n
}

func (m *SetBlockIndexerRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovPruning(uint64(m.Height))
	}
	return n
}

func (m *SetBlockIndexerRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBlockIndexerRetainHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBlockIndexerRetainHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovPruning(uint64(m.Height))
	}
	return n
}

func sovPruning(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPruning(x uint64) (n int) {
	return sovPruning(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SetBlockRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetBlockRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetBlockRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetBlockRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetBlockRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetBlockRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppRetainHeight", wireType)
			}
			m.AppRetainHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppRetainHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PruningServiceRetainHeight", wireType)
			}
			m.PruningServiceRetainHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PruningServiceRetainHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetBlockResultsRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetBlockResultsRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetBlockResultsRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetBlockResultsRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetBlockResultsRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetBlockResultsRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockResultsRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockResultsRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockResultsRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockResultsRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockResultsRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockResultsRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PruningServiceRetainHeight", wireType)
			}
			m.PruningServiceRetainHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PruningServiceRetainHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetTxIndexerRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetTxIndexerRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetTxIndexerRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetTxIndexerRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetTxIndexerRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetTxIndexerRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTxIndexerRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTxIndexerRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTxIndexerRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTxIndexerRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTxIndexerRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTxIndexerRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetBlockIndexerRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetBlockIndexerRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetBlockIndexerRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetBlockIndexerRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetBlockIndexerRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetBlockIndexerRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockIndexerRetainHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockIndexerRetainHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockIndexerRetainHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockIndexerRetainHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockIndexerRetainHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockIndexerRetainHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPruning(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPruning
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPruning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPruning
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPruning
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPruning
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPruning        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPruning          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPruning = fmt.Errorf("proto: unexpected end of group")
)
