version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v1.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v0.38.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v0.37.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v0.34.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  ###################################
  ##
  ## Update All Go Dependencies

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v1.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "v0.38.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "v0.37.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "v0.34.x"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge
