queue_rules:
  - name: default
    conditions:
      - base=main
      - label=automerge

pull_request_rules:
  - name: Automerge to main
    conditions:
      - base=main
      - label=automerge
    actions:
      queue:
        method: squash
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
  - name: backport patches to v0.37.x branch
    conditions:
      - base=main
      - label=backport-to-v0.37.x
    actions:
      backport:
        branches:
          - v0.37.x
  - name: backport patches to v0.34.x branch
    conditions:
      - base=main
      - label=backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
