pull_request_rules:
  - name: Make sure PR are up to date before merging
    description: >-
      This automatically updates PRs when they are out-of-date with the base
      branch to avoid semantic conflicts (next step is using a merge queue).
    conditions:
      - '-draft'
    actions:
      update:
  - name: backport patches to v0.38.x-experimental branch
    conditions:
      - base=v0.38.x
      - label=backport-to-v0.38.x-experimental
    actions:
      backport:
        branches:
          - v0.38.x-experimental
  - name: backport patches to v1.x branch
    conditions:
      - base=main
      - label=backport-to-v1.x
    actions:
      backport:
        branches:
          - v1.x
  - name: backport patches to v0.38.x branch
    conditions:
      - base=main
      - label=backport-to-v0.38.x
    actions:
      backport:
        branches:
          - v0.38.x
  - name: backport patches to v0.37.x branch
    conditions:
      - base=main
      - label=backport-to-v0.37.x
    actions:
      backport:
        branches:
          - v0.37.x
  - name: backport patches to v0.34.x branch
    conditions:
      - base=main
      - label=backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
