pull_request_rules:
  - name: backport patches to v1.x branch
    conditions:
      - base=main
      - label=backport-to-v1.x
    actions:
      backport:
        branches:
          - v1.x
  - name: backport patches to v0.38.x branch
    conditions:
      - base=main
      - label=backport-to-v0.38.x
    actions:
      backport:
        branches:
          - v0.38.x
  - name: backport patches to v0.37.x branch
    conditions:
      - base=main
      - label=backport-to-v0.37.x
    actions:
      backport:
        branches:
          - v0.37.x
  - name: backport patches to v0.34.x branch
    conditions:
      - base=main
      - label=backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
