pull_request_rules:
  - name: automatically merge backport (v0.34.x)
    description: automatically merge backport if it passes tests and there are no conflicts (v0.34.x)
    conditions:
      - '-label=manual-backport'
      - author=mergify[bot]
      - head~=mergify/bp/
      - base=v0.34.x
      - check-success=check-mocks
      - check-success=golangci-lint
      - check-success=Super linter
      - check-success=split-test-files
      - check-success=cleanup-runs
      - check-success=e2e-test
      - check-success=check-proto
      - check-success=Build
      - check-success=tests (00)
      - check-success=tests (01)
      - check-success=tests (02)
      - check-success=tests (03)
      - check-success=test_abci_cli
      - check-success=test_apps
    actions:
      merge:
        method: merge
  - name: automatically merge backport (v0.38.x and v0.37.x)
    description: automatically merge backport if it passes tests and there are no conflicts (v0.38.x and v0.37.x)
    conditions:
      - '-label=manual-backport'
      - author=mergify[bot]
      - head~=mergify/bp/
      - '-base=v1.x'
      - '-base=v0.34.x'
      - check-success=Build (arm, linux)
      - check-success=check
      - check-success=golangci-lint
      - check-success=e2e-test
      - check-success=tests (00)
      - check-success=tests (01)
      - check-success=tests (02)
      - check-success=tests (03)
      - check-success=tests (04)
      - check-success=tests (05)
      - check-success=test_abci_cli
      - check-success=test_apps
    actions:
      merge:
        method: merge
  - name: automatically merge backport (v1.x)
    description: automatically merge backport if it passes tests and there are no conflicts (v1.x)
    conditions:
      - '-label=manual-backport'
      - author=mergify[bot]
      - head~=mergify/bp/
      - base=v1.x
      - check-success=Build (arm, linux)
      - check-success=check
      - check-success=check-mocks-metrics
      - check-success=lint
      - check-success=e2e-test
      - check-success=tests (00)
      - check-success=tests (01)
      - check-success=tests (02)
      - check-success=tests (03)
      - check-success=tests (04)
      - check-success=tests (05)
      - check-success=test_abci_cli
      - check-success=test_apps
      - check-success=check-proto
    actions:
      merge:
        method: merge
  - name: Attach backport-to-v0.38.x-experimental label to PR
    description: >-
      Assign backport-to-v0.38.x-experimental label to any PR targeting v0.38.x
      branch
    conditions:
      - base=v0.38.x
    actions:
      label:
        toggle:
          - backport-to-v0.38.x-experimental
  - name: Make sure PR are up to date before merging
    description: >-
      This automatically updates PRs when they are out-of-date with the base
      branch to avoid semantic conflicts (next step is using a merge queue).
    conditions:
      - '-draft'
    actions:
      update:
  - name: backport patches to v0.38.x-experimental branch
    conditions:
      - base=v0.38.x
      - label=backport-to-v0.38.x-experimental
    actions:
      backport:
        branches:
          - v0.38.x-experimental
        assignees:
          - "{{ author }}"
  - name: backport patches to v1.x branch
    conditions:
      - base=main
      - label=backport-to-v1.x
    actions:
      backport:
        branches:
          - v1.x
        assignees:
          - "{{ author }}"
  - name: backport patches to v0.38.x branch
    conditions:
      - base=main
      - label=backport-to-v0.38.x
    actions:
      backport:
        branches:
          - v0.38.x
        assignees:
          - "{{ author }}"
  - name: backport patches to v0.37.x branch
    conditions:
      - base=main
      - label=backport-to-v0.37.x
    actions:
      backport:
        branches:
          - v0.37.x
        assignees:
          - "{{ author }}"
  - name: backport patches to v0.34.x branch
    conditions:
      - base=main
      - label=backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
        assignees:
          - "{{ author }}"
