run:
  tests: true
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - revive
    - gofumpt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - gofmt
        - goimport
        - gosec
        - noctx
        - paralleltest
        - testpackage
        - tparallel
    - path: \.pb\.go
      linters:
        - gofmt
        - goimports
        - govet
        - stylecheck
  max-same-issues: 10000
  max-issues-per-linter: 10000
linters-settings:
  dogsled:
    max-blank-identifiers: 3
  goconst:
    ignore-tests: true
  misspell:
    locale: US
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/cometbft/cometbft, github.com/cometbft/cometbft-db, github.com/cometbft/cometbft-load-test)
    custom-order: true
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/BurntSushi/toml
          - github.com/Masterminds/semver/v3
          - github.com/cometbft
          - github.com/cosmos
          - github.com/creachadair/atomicfile
          - github.com/creachadair/tomledit
          - github.com/decred/dcrd/dcrec/secp256k1/v4
          - github.com/dgraph-io/badger/v4
          - github.com/ethereum/go-ethereum/crypto
          - github.com/go-git/go-git/v5
          - github.com/google
          - github.com/gorilla/websocket
          - github.com/hashicorp/golang-lru/v2
          - github.com/lib/pq
          - github.com/libp2p/go-buffer-pool
          - github.com/lmittmann/tint
          - github.com/minio/highwayhash
          - github.com/mitchellh/mapstructure
          - github.com/oasisprotocol/curve25519-voi
          - github.com/pelletier/go-toml/v2
          - github.com/pkg/errors
          - github.com/prometheus
          - github.com/rcrowley/go-metrics
          - github.com/rs/cors
          - github.com/snikch/goodman
          - github.com/spf13
          - github.com/stretchr/testify/require
          - github.com/syndtr/goleveldb
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/adlio/schema
          - github.com/btcsuite/btcd
          - github.com/cometbft
          - github.com/cosmos
          - github.com/dgraph-io/badger/v4
          - github.com/fortytw2/leaktest
          - github.com/google/uuid
          - github.com/gorilla/websocket
          - github.com/lib/pq
          - github.com/oasisprotocol/curve25519-voi/primitives/merlin
          - github.com/ory/dockertest
          - github.com/pkg/errors
          - github.com/prometheus/client_golang/prometheus
          - github.com/prometheus/client_golang/prometheus/promhttp
          - github.com/spf13
          - github.com/stretchr/testify
          - github.com/decred/dcrd/dcrec/secp256k1/v4

  revive:
    enable-all-rules: true
    rules:
      - name: comment-spacings # temporarily disabled
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: deep-exit
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: add-constant
        disabled: true
      - name: empty-lines
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: modifies-value-receiver
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: defer
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: unhandled-error
        disabled: true
        arguments:
          - "fmt.Printf"
          - "fmt.Print"
          - "fmt.Println"
  gosec:
    excludes:
      - G115
