run:
  tests: false
  timeout: 5m

linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - dupword
    - errname
    - errorlint
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - goerr113
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacebloat
    - interfacer
    - ireturn
    - lll
    - maintidx
    - maligned
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - predeclared
    - tagliatelle
    - typecheck
    - varnamelen
    - wrapcheck
    - wsl
    - scopelint
    - unparam
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: \.pb\.go
      linters:
        - gofmt
        - goimports
        - govet
        - stylecheck
  max-same-issues: 50

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  goconst:
    ignore-tests: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/cometbft
          - github.com/cosmos
          - github.com/btcsuite/btcd/btcec/v2
          - github.com/BurntSushi/toml
          - github.com/go-git/go-git/v5
          - github.com/go-kit
          - github.com/go-logfmt/logfmt
          - github.com/gofrs/uuid
          - github.com/google
          - github.com/gorilla/websocket
          - github.com/informalsystems/tm-load-test/pkg/loadtest
          - github.com/lib/pq
          - github.com/libp2p/go-buffer-pool
          - github.com/Masterminds/semver/v3
          - github.com/minio/highwayhash
          - github.com/oasisprotocol/curve25519-voi
          - github.com/pkg/errors
          - github.com/prometheus
          - github.com/rcrowley/go-metrics
          - github.com/rs/cors
          - github.com/snikch/goodman
          - github.com/spf13
          - github.com/stretchr/testify/require
          - github.com/syndtr/goleveldb
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/cosmos
          - github.com/cometbft
          - github.com/adlio/schema
          - github.com/btcsuite/btcd
          - github.com/fortytw2/leaktest
          - github.com/go-kit
          - github.com/google/uuid
          - github.com/gorilla/websocket
          - github.com/lib/pq
          - github.com/oasisprotocol/curve25519-voi/primitives/merlin
          - github.com/ory/dockertest
          - github.com/pkg/errors
          - github.com/prometheus/client_golang/prometheus/promhttp
          - github.com/spf13
          - github.com/stretchr/testify
