// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	p2p "github.com/cometbft/cometbft/p2p"
	mock "github.com/stretchr/testify/mock"
)

// nodeInfoAddress is an autogenerated mock type for the nodeInfoAddress type
type nodeInfoAddress struct {
	mock.Mock
}

// NetAddress provides a mock function with no fields
func (_m *nodeInfoAddress) NetAddress() (*p2p.NetAddress, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NetAddress")
	}

	var r0 *p2p.NetAddress
	var r1 error
	if rf, ok := ret.Get(0).(func() (*p2p.NetAddress, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *p2p.NetAddress); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*p2p.NetAddress)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newNodeInfoAddress creates a new instance of nodeInfoAddress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNodeInfoAddress(t interface {
	mock.TestingT
	Cleanup(func())
}) *nodeInfoAddress {
	mock := &nodeInfoAddress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
