// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// receiveCbFunc is an autogenerated mock type for the receiveCbFunc type
type receiveCbFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: chID, msgBytes
func (_m *receiveCbFunc) Execute(chID byte, msgBytes []byte) {
	_m.Called(chID, msgBytes)
}

// newReceiveCbFunc creates a new instance of receiveCbFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newReceiveCbFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *receiveCbFunc {
	mock := &receiveCbFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
