// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	p2p "github.com/cometbft/cometbft/p2p"
	mock "github.com/stretchr/testify/mock"
)

// SwitchOption is an autogenerated mock type for the SwitchOption type
type SwitchOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SwitchOption) Execute(_a0 *p2p.Switch) {
	_m.Called(_a0)
}

// NewSwitchOption creates a new instance of SwitchOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSwitchOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *SwitchOption {
	mock := &SwitchOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
