FROM gcr.io/distroless/static-debian11:debug

COPY build/node /app
COPY docker/entrypoint-fast /usr/bin/entrypoint-builtin

WORKDIR /cometbft
VOLUME /cometbft
ENV CMTHOME=/cometbft
ENV GORACE "halt_on_error=1"

EXPOSE 26656 26657 26660 6060
ENTRYPOINT ["/usr/bin/entrypoint-builtin"]
STOPSIGNAL SIGTERM
