#!/usr/bin/env bash

set -e

if [ -f /cometbft/emulate-latency.sh ]; then
    /cometbft/emulate-latency.sh
fi

# Forcibly remove any stray UNIX sockets left behind from previous runs
rm -rf /var/run/privval.sock /var/run/app.sock

/usr/bin/app /cometbft/config/app.toml
