// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrInvalidBlock is an autogenerated mock type for the ErrInvalidBlock type
type ErrInvalidBlock struct {
	mock.Mock
}

// Error provides a mock function with no fields
func (_m *ErrInvalidBlock) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewErrInvalidBlock creates a new instance of ErrInvalidBlock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrInvalidBlock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrInvalidBlock {
	mock := &ErrInvalidBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
