# Verify that important design docs have ToC entries.
name: Check documentation ToC
on:
  pull_request:
    push:
      branches:
        - v0.38.x

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
        with:
          PATTERNS: |
            docs/architecture/**
            docs/rfc/**
      - run: make check-docs-toc
        if: env.GIT_DIFF
