name: "Notify about breaking changes"

on:
  push:
    branches:
      - v1.x
    paths:
      - ".changelog/unreleased/breaking-changes/**"

jobs:
  notify:
    name: Notify about breaking changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v1.x'

      - name: Detect new files in directory
        id: detect-new-files
        run: |
          DIRECTORY=".changelog/unreleased/breaking-changes"

          # Get a list of new files in the directory (added in the last commit)
          NEW_FILES=$(git diff --name-status HEAD^..HEAD $DIRECTORY | grep "^A" | awk '{print $2}')

          if [ -n "$NEW_FILES" ]; then
            echo "New files detected: $NEW_FILES"
            echo "::set-output name=new_files::$NEW_FILES"
          else
            echo "No new files detected"
            echo "::set-output name=new_files::none"
          fi

      - name: Read the content of new files
        if: steps.detect-new-files.outputs.new_files != 'none'
        id: read-content
        run: |
          NEW_FILES="${{ steps.detect-new-files.outputs.new_files }}"
          CONTENT=""

          for FILE in $NEW_FILES; do
            FILE_CONTENT=$(cat $FILE)
            CONTENT="$CONTENT\n---\n$FILE_CONTENT\n"
          done

          echo "$CONTENT"
          echo "::set-output name=file_content::$CONTENT"

      - name: Post to a Slack channel
        id: slack
        if: steps.read-content.outputs.file_content != ''
        uses: slackapi/slack-github-action@v2.1.0
        with:
          channel-id: 'C03Q5J9SXS8' # cometbft-engineering
          # channel-id: 'shared-sdk-comet'
          payload: |
            text: "New breaking changes (pushed in ${{ github.event.pull_request.html_url || github.event.head_commit.url }}):"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ steps.read-content.outputs.file_content }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
