name: Protobuf Lint
on:
  pull_request:
    paths:
      - 'proto/**'
  push:
    branches:
      - v0.38.x
    paths:
      - 'proto/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          input: 'proto'
          version: '1.66.0'
